/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ComboBox;
import controlador.EstudianteCtrl;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import modelo.Estudiante;

/**
 *
 * @author polod
 */
public class AgregarEstudiante extends javax.swing.JFrame {

    private DefaultTableModel model;
    private JTable tabla;
    
    
    /**
     * Creates new form AgregarEstudiante
     */
    public AgregarEstudiante() {
        this.setUndecorated(true);
        initComponents();
        setLocationRelativeTo(null);
    }
    
    // F
        
    //recibe el  modelo que lista los estudiantes
    public void setModel(DefaultTableModel model){
        this.model = model;   
    }
    
    //recibe la tabla donde se listan los estudiantes
    public void setTabla(JTable tbl){
        this.tabla = tbl;   
    }
    
    public void ActualizarDatosTabla(){
        EstudianteCtrl tblEstu = new EstudianteCtrl(this.tabla);
        model.setRowCount(0);
        tblEstu.getEstudiantes();
        dispose();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JPanel();
        txtEdad = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        CMBXGenero = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtCorreo = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtApellidos = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAcudiente = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelfAcu = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        CMBXProfesor = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        CMBXCurso = new javax.swing.JComboBox<>();
        btnAñadir = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Contenedor.setBackground(new java.awt.Color(255, 255, 255));
        Contenedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(250, 125, 85)));
        Contenedor.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ContenedorAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        Contenedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEdad.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtEdad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Contenedor.add(txtEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 150, 30));

        txtDireccion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Contenedor.add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 150, 30));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel6.setText("Dirección:");
        Contenedor.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 30));

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel1.setText("Identificación:");
        Contenedor.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel7.setText("Genero:");
        Contenedor.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, 30));

        txtIdentificacion.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtIdentificacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Contenedor.add(txtIdentificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 150, 30));

        CMBXGenero.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CMBXGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        CMBXGenero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Contenedor.add(CMBXGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 150, 30));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel3.setText("Nombres:");
        Contenedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 30));

        txtCorreo.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtCorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Contenedor.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 350, 150, 30));

        txtNombres.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtNombres.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Contenedor.add(txtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 150, 30));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel8.setText("Correo:");
        Contenedor.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, 30));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setText("Apellidos:");
        Contenedor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, 30));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel9.setText("Telefono:");
        Contenedor.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, 30));

        txtApellidos.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtApellidos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Contenedor.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, 150, 30));

        txtTelefono.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTelefono.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelefonoActionPerformed(evt);
            }
        });
        Contenedor.add(txtTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 150, 30));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel5.setText("Edad:");
        Contenedor.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, -1, 30));

        jLabel10.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel10.setText("Acudiente:");
        Contenedor.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, -1, 30));

        txtAcudiente.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtAcudiente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtAcudiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAcudienteActionPerformed(evt);
            }
        });
        Contenedor.add(txtAcudiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 150, 30));

        jLabel11.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel11.setText("Telf. Acudiente:");
        Contenedor.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, 30));

        txtTelfAcu.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        txtTelfAcu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        txtTelfAcu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTelfAcuActionPerformed(evt);
            }
        });
        Contenedor.add(txtTelfAcu, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 470, 150, 30));

        jLabel12.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel12.setText("Profesor:");
        Contenedor.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, 30));

        CMBXProfesor.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CMBXProfesor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Contenedor.add(CMBXProfesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 150, 30));

        jLabel13.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel13.setText("Curso:");
        Contenedor.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, -1, 30));

        CMBXCurso.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        CMBXCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        Contenedor.add(CMBXCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 150, 30));

        btnAñadir.setBackground(new java.awt.Color(250, 125, 85));
        btnAñadir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnAñadir.setForeground(new java.awt.Color(255, 255, 255));
        btnAñadir.setText("Añadir");
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        Contenedor.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 600, 110, 30));

        btnCancelar.setBackground(new java.awt.Color(250, 125, 85));
        btnCancelar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        Contenedor.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 600, 110, 30));

        jPanel1.setBackground(new java.awt.Color(250, 125, 85));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Añadir Estudiante");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );

        Contenedor.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 80));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void txtAcudienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAcudienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAcudienteActionPerformed

    private void txtTelfAcuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelfAcuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelfAcuActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void ContenedorAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ContenedorAncestorAdded
        comboxProf = new ComboBox(CMBXProfesor);
        comboxProf.getProfesoresComboBox();
        comboxCurso = new ComboBox(CMBXCurso);
        comboxCurso.getCursosComboBox();
    }//GEN-LAST:event_ContenedorAncestorAdded

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        String genero = (String)CMBXGenero.getSelectedItem();
      
        try {
            Estudiante estu = new Estudiante(Integer.parseInt(txtIdentificacion.getText()), txtNombres.getText(), txtApellidos.getText(), Integer.parseInt(txtEdad.getText()), txtDireccion.getText(), genero, txtCorreo.getText(), txtTelefono.getText(),txtAcudiente.getText() , txtTelfAcu.getText(), CMBXProfesor,CMBXCurso ,  comboxProf, comboxCurso);        
            EstudianteCtrl addEstu = new EstudianteCtrl();
            boolean agregado = addEstu.setEstudiantes(estu);
            if(agregado) ActualizarDatosTabla();
               
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Algunos datos estan ingresados de forma erronea, verifiquelos.");  
        }
            
    }//GEN-LAST:event_btnAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarEstudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarEstudiante().setVisible(true);
            }
        });
    }
    
    
     private ComboBox comboxProf; 
     private ComboBox comboxCurso;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CMBXCurso;
    private javax.swing.JComboBox<String> CMBXGenero;
    private javax.swing.JComboBox<String> CMBXProfesor;
    private javax.swing.JPanel Contenedor;
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtAcudiente;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelfAcu;
    // End of variables declaration//GEN-END:variables
}
