/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.EstudianteCtrl;
import controlador.ProfesorCtrl;
import controlador.coordinador;
import java.awt.Color;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author polod
 */
public class EliminarProfesor extends javax.swing.JFrame {
    private coordinador miCoordinador;
    int MouseX;
    int MouseY;
    private VentanaLogin milogin;
    private DefaultTableModel model;
    private JTable tabla;
    private ProfesorCtrl profCtrl;
    
    /**
     * Creates new form EliminarProfesor
     */
    public EliminarProfesor() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * 
     * 
     */
    
    
       //METODOS CREADOS 
    
   //recibe los datos de la vista de listarEstdiante para mostrarlo en cada campo
 
    //recibe el  modelo que lista los estudiantes
    public void setModel(DefaultTableModel model){
        this.model = model;   
    }
    
    //recibe la tabla donde se listan los estudiantes
    public void setTabla(JTable tbl){
        this.tabla = tbl;   
    }
    
    public void ActualizarDatosTabla(){
        profCtrl= new ProfesorCtrl(this.tabla);
        model.setRowCount(0);
        profCtrl.getProfesores();
        dispose();
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpBg = new javax.swing.JPanel();
        AlterJpHeader = new javax.swing.JPanel();
        JpExitBtn = new javax.swing.JPanel();
        txtJpExitBtn = new javax.swing.JLabel();
        txtAlertaa = new javax.swing.JLabel();
        txtAlertaa1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        fondoCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JLabel();
        fondoEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        JpBg.setBackground(new java.awt.Color(255, 255, 255));
        JpBg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 102)));
        JpBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AlterJpHeader.setBackground(new java.awt.Color(250, 125, 85));
        AlterJpHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                AlterJpHeaderMouseDragged(evt);
            }
        });
        AlterJpHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                AlterJpHeaderMousePressed(evt);
            }
        });
        AlterJpHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JpExitBtn.setOpaque(false);

        txtJpExitBtn.setFont(new java.awt.Font("Yu Gothic Medium", 0, 20)); // NOI18N
        txtJpExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        txtJpExitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJpExitBtn.setText("X");
        txtJpExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtJpExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJpExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtJpExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtJpExitBtnMouseExited(evt);
            }
        });

        javax.swing.GroupLayout JpExitBtnLayout = new javax.swing.GroupLayout(JpExitBtn);
        JpExitBtn.setLayout(JpExitBtnLayout);
        JpExitBtnLayout.setHorizontalGroup(
            JpExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtJpExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        JpExitBtnLayout.setVerticalGroup(
            JpExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtJpExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        AlterJpHeader.add(JpExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 0, 40, 35));

        JpBg.add(AlterJpHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 35));

        txtAlertaa.setFont(new java.awt.Font("Roboto", 0, 17)); // NOI18N
        txtAlertaa.setForeground(new java.awt.Color(102, 102, 102));
        txtAlertaa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAlertaa.setText("¿Está seguro que desea eliminar a este estudinate?");
        JpBg.add(txtAlertaa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 390, 40));

        txtAlertaa1.setFont(new java.awt.Font("Roboto", 1, 25)); // NOI18N
        txtAlertaa1.setForeground(new java.awt.Color(51, 51, 51));
        txtAlertaa1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtAlertaa1.setText("Eliminar Estudiante");
        JpBg.add(txtAlertaa1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 390, 40));

        btnCancelar.setBackground(new java.awt.Color(250, 125, 85));
        btnCancelar.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        JpBg.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 120, 30));

        fondoCancelar.setBackground(new java.awt.Color(250, 125, 85));
        fondoCancelar.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        fondoCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn2Norm.png"))); // NOI18N
        fondoCancelar.setBorder(null);
        fondoCancelar.setBorderPainted(false);
        fondoCancelar.setContentAreaFilled(false);
        fondoCancelar.setFocusPainted(false);
        fondoCancelar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn2Press.png"))); // NOI18N
        fondoCancelar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn2Hover.png"))); // NOI18N
        JpBg.add(fondoCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 120, 30));

        btnEliminar.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEliminar.setText("Eliminar");
        btnEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });
        JpBg.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 120, 30));

        fondoEliminar.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        fondoEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn2Norm.png"))); // NOI18N
        fondoEliminar.setBorder(null);
        fondoEliminar.setBorderPainted(false);
        fondoEliminar.setContentAreaFilled(false);
        fondoEliminar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn2Press.png"))); // NOI18N
        fondoEliminar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/btn2Hover.png"))); // NOI18N
        JpBg.add(fondoEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 120, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpBg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpBg, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtJpExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJpExitBtnMouseClicked
        dispose();
    }//GEN-LAST:event_txtJpExitBtnMouseClicked

    private void txtJpExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJpExitBtnMouseEntered
        JpExitBtn.setBackground(Color.red);
        JpExitBtn.setOpaque(true);
        txtJpExitBtn.setForeground(Color.white);
    }//GEN-LAST:event_txtJpExitBtnMouseEntered

    private void txtJpExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJpExitBtnMouseExited
        JpExitBtn.setBackground(Color.white);
        JpExitBtn.setOpaque(false);
        txtJpExitBtn.setForeground(Color.white);
    }//GEN-LAST:event_txtJpExitBtnMouseExited

    private void AlterJpHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterJpHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-MouseX, y-MouseY);
    }//GEN-LAST:event_AlterJpHeaderMouseDragged

    private void AlterJpHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AlterJpHeaderMousePressed
        MouseX=evt.getX();
        MouseY=evt.getY();
    }//GEN-LAST:event_AlterJpHeaderMousePressed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        profCtrl = new ProfesorCtrl();
        boolean elimindado = profCtrl.getDataDeleteProfesor(tabla);
        System.out.println("hola");
        if(elimindado) this.ActualizarDatosTabla();

    }//GEN-LAST:event_btnEliminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EliminarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EliminarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EliminarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EliminarProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EliminarProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AlterJpHeader;
    private javax.swing.JPanel JpBg;
    private javax.swing.JPanel JpExitBtn;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JLabel btnEliminar;
    private javax.swing.JButton fondoCancelar;
    private javax.swing.JButton fondoEliminar;
    private javax.swing.JLabel txtAlertaa;
    private javax.swing.JLabel txtAlertaa1;
    private javax.swing.JLabel txtJpExitBtn;
    // End of variables declaration//GEN-END:variables
}
