/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ProfesorCtrl;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author polod
 */
public class ListarProfesores extends javax.swing.JPanel {

    boolean cargar = false;
    DefaultTableModel modelo;
    ProfesorCtrl profCtrl;
    
    /**
     * Creates new form ListarProfesores
     */
    public ListarProfesores() {
        initComponents();
    }
    
     public void ActualizarDatosTabla(){
        profCtrl= new ProfesorCtrl(tblProfesores);
        modelo.setRowCount(0);
        profCtrl.getProfesores();
       
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblProfesores = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnActualizar1 = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        tblProfesores.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        tblProfesores.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tblProfesores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Identificacion", "Nombre", "Apellido", "Edad", "direccion", "Genero", "Correo", "Telefono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProfesores.setGridColor(new java.awt.Color(255, 255, 255));
        tblProfesores.setOpaque(false);
        tblProfesores.setSelectionBackground(new java.awt.Color(250, 125, 85));
        tblProfesores.setSelectionForeground(new java.awt.Color(251, 251, 251));
        tblProfesores.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblProfesores.getTableHeader().setResizingAllowed(false);
        tblProfesores.getTableHeader().setReorderingAllowed(false);
        tblProfesores.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblProfesoresAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tblProfesores);
        if (tblProfesores.getColumnModel().getColumnCount() > 0) {
            tblProfesores.getColumnModel().getColumn(0).setResizable(false);
            tblProfesores.getColumnModel().getColumn(1).setResizable(false);
            tblProfesores.getColumnModel().getColumn(2).setResizable(false);
            tblProfesores.getColumnModel().getColumn(3).setResizable(false);
            tblProfesores.getColumnModel().getColumn(4).setResizable(false);
            tblProfesores.getColumnModel().getColumn(5).setResizable(false);
            tblProfesores.getColumnModel().getColumn(6).setResizable(false);
            tblProfesores.getColumnModel().getColumn(7).setResizable(false);
        }

        jButton1.setBackground(new java.awt.Color(250, 125, 85));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(250, 125, 85));
        btnActualizar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnActualizar1.setBackground(new java.awt.Color(250, 125, 85));
        btnActualizar1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnActualizar1.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar1.setText("Borrar");
        btnActualizar1.setBorder(null);
        btnActualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizar1ActionPerformed(evt);
            }
        });

        btnRecargar.setBackground(new java.awt.Color(250, 125, 85));
        btnRecargar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRecargar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecargar.setText("Recargar");
        btnRecargar.setBorder(null);
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btnRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnActualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblProfesoresAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblProfesoresAncestorAdded
          if(!cargar){
              
            profCtrl = new ProfesorCtrl(tblProfesores);
            modelo = profCtrl.getProfesores();
            cargar = true;            
          }
  
    }//GEN-LAST:event_tblProfesoresAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AgregarProfesor addProf = new AgregarProfesor();
        addProf.setVisible(true);
        addProf.setModel(modelo);
        addProf.setTabla(tblProfesores); 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        profCtrl.setUpdateData(tblProfesores, modelo);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnActualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizar1ActionPerformed
        profCtrl.mostrarVentanaEliminar(tblProfesores, modelo);
    }//GEN-LAST:event_btnActualizar1ActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        this.ActualizarDatosTabla();
    }//GEN-LAST:event_btnRecargarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnActualizar1;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblProfesores;
    // End of variables declaration//GEN-END:variables
}
