/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CursoCtrl;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author polod
 */
public class ListarCursos extends javax.swing.JPanel {

    boolean cargar = false;
    DefaultTableModel modelo;
    CursoCtrl cursoCtrl;
    /**
     * Creates new form ListarCursos
     */
    public ListarCursos() {
        initComponents();
    }
    
             
    public void ActualizarDatosTabla(){
        CursoCtrl tblCurso = new CursoCtrl(tbLCursos);
        modelo.setRowCount(0);
        tblCurso.getCursos();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tbLCursos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnRecargar = new javax.swing.JButton();
        btnFlitrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tbLCursos.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tbLCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Cantidad", "Profesor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLCursos.setGridColor(new java.awt.Color(255, 255, 255));
        tbLCursos.setSelectionBackground(new java.awt.Color(250, 125, 85));
        tbLCursos.setSelectionForeground(new java.awt.Color(252, 251, 251));
        tbLCursos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbLCursos.getTableHeader().setResizingAllowed(false);
        tbLCursos.getTableHeader().setReorderingAllowed(false);
        tbLCursos.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbLCursosAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane2.setViewportView(tbLCursos);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 96, 890, 450));

        jButton1.setBackground(new java.awt.Color(250, 125, 85));
        jButton1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 110, 35));

        btnActualizar.setBackground(new java.awt.Color(250, 125, 85));
        btnActualizar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar");
        btnActualizar.setBorder(null);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 110, 35));

        btnBorrar.setBackground(new java.awt.Color(250, 125, 85));
        btnBorrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrar.setText("Borrar");
        btnBorrar.setBorder(null);
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 110, 35));

        btnRecargar.setBackground(new java.awt.Color(250, 125, 85));
        btnRecargar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnRecargar.setForeground(new java.awt.Color(255, 255, 255));
        btnRecargar.setText("Recargar");
        btnRecargar.setBorder(null);
        btnRecargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecargarActionPerformed(evt);
            }
        });
        add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 50, 110, 35));

        btnFlitrar.setBackground(new java.awt.Color(250, 125, 85));
        btnFlitrar.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFlitrar.setForeground(new java.awt.Color(255, 255, 255));
        btnFlitrar.setText("Filtrar");
        btnFlitrar.setBorder(null);
        btnFlitrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlitrarActionPerformed(evt);
            }
        });
        add(btnFlitrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 110, 35));
    }// </editor-fold>//GEN-END:initComponents

    private void tbLCursosAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbLCursosAncestorAdded
        if(!cargar){
            cursoCtrl = new CursoCtrl(tbLCursos);
            this.modelo =  cursoCtrl.getCursos();
            cargar = true;
        }
    }//GEN-LAST:event_tbLCursosAncestorAdded

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AgregarCurso addCurso = new AgregarCurso();
        addCurso.setVisible(true);
        addCurso.setModel(modelo);
        addCurso.setTabla(tbLCursos);      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        cursoCtrl= new CursoCtrl();
        cursoCtrl.setUpdateData(tbLCursos,this.modelo);
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        cursoCtrl.mostrarVentanaEliminar(tbLCursos, modelo);
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnRecargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecargarActionPerformed
        this.ActualizarDatosTabla();
    }//GEN-LAST:event_btnRecargarActionPerformed

    private void btnFlitrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlitrarActionPerformed
        FiltrarCursoPorProfesor filtrar = new FiltrarCursoPorProfesor();
        filtrar.setVisible(true);
        filtrar.setModel(modelo);
        filtrar.setTabla(tbLCursos);
        
    }//GEN-LAST:event_btnFlitrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnFlitrar;
    private javax.swing.JButton btnRecargar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbLCursos;
    // End of variables declaration//GEN-END:variables
}
