package vista;

import controlador.LoginCtrl;
import controlador.coordinador;
import java.awt.Color;


public class VentanaLogin extends javax.swing.JFrame {

    /**
     * Creates new form VentanaLogin
     */
    
    int mouseX;
    int mouseY;
    private coordinador miCoordinador;
    AlertaError mialerta2 = new AlertaError();
    AlertaContraseña mialerta3 = new AlertaContraseña();
    public VentanaLogin() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JpBackground = new javax.swing.JPanel();
        JpHeader = new javax.swing.JPanel();
        txtJpExitBtn = new javax.swing.JLabel();
        txtJpMinBtN = new javax.swing.JLabel();
        JpExitBtn = new javax.swing.JPanel();
        JpMinBtN = new javax.swing.JPanel();
        JpSecondBg = new javax.swing.JPanel();
        JpSenaIcon = new javax.swing.JLabel();
        txtDescription = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        Jsepusername = new javax.swing.JSeparator();
        JpUserName = new javax.swing.JLabel();
        JsePassword = new javax.swing.JSeparator();
        JpPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        JCheckShowPassword = new javax.swing.JCheckBox();
        JpLoginBtn = new javax.swing.JPanel();
        btnLogin = new javax.swing.JLabel();
        JpUser = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        JpBackground.setBackground(new java.awt.Color(255, 255, 255));
        JpBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JpHeader.setBackground(new java.awt.Color(255, 255, 255));
        JpHeader.setOpaque(false);
        JpHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                JpHeaderMouseDragged(evt);
            }
        });
        JpHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JpHeaderMousePressed(evt);
            }
        });
        JpHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtJpExitBtn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtJpExitBtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJpExitBtn.setText("x");
        txtJpExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtJpExitBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        txtJpExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJpExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtJpExitBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtJpExitBtnMouseExited(evt);
            }
        });
        JpHeader.add(txtJpExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, 40, 35));

        txtJpMinBtN.setBackground(new java.awt.Color(225, 225, 225));
        txtJpMinBtN.setFont(new java.awt.Font("Yu Gothic Medium", 1, 36)); // NOI18N
        txtJpMinBtN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtJpMinBtN.setText("-");
        txtJpMinBtN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtJpMinBtN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtJpMinBtNMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtJpMinBtNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtJpMinBtNMouseExited(evt);
            }
        });
        JpHeader.add(txtJpMinBtN, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, 40, 35));

        JpExitBtn.setForeground(new java.awt.Color(255, 255, 255));
        JpExitBtn.setOpaque(false);
        JpExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JpExitBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                JpExitBtnMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout JpExitBtnLayout = new javax.swing.GroupLayout(JpExitBtn);
        JpExitBtn.setLayout(JpExitBtnLayout);
        JpExitBtnLayout.setHorizontalGroup(
            JpExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        JpExitBtnLayout.setVerticalGroup(
            JpExitBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        JpHeader.add(JpExitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 0, -1, -1));

        JpMinBtN.setBackground(new java.awt.Color(226, 226, 226));
        JpMinBtN.setOpaque(false);

        javax.swing.GroupLayout JpMinBtNLayout = new javax.swing.GroupLayout(JpMinBtN);
        JpMinBtN.setLayout(JpMinBtNLayout);
        JpMinBtNLayout.setHorizontalGroup(
            JpMinBtNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        JpMinBtNLayout.setVerticalGroup(
            JpMinBtNLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        JpHeader.add(JpMinBtN, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 0, -1, -1));

        JpBackground.add(JpHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 40));

        JpSecondBg.setBackground(new java.awt.Color(252, 252, 252));
        JpSecondBg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JpSenaIcon.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        JpSenaIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JpSenaIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/faviconSena2.png"))); // NOI18N
        JpSenaIcon.setText("  Login");
        JpSecondBg.add(JpSenaIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 180, 100));

        txtDescription.setFont(new java.awt.Font("Roboto Light", 0, 15)); // NOI18N
        txtDescription.setForeground(new java.awt.Color(153, 153, 153));
        txtDescription.setText("Bienvenido devuelta apreciado usuario");
        JpSecondBg.add(txtDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 350, 50));

        txtUserName.setBackground(new java.awt.Color(252, 252, 252));
        txtUserName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtUserName.setBorder(null);
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        JpSecondBg.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 290, 360, 30));

        Jsepusername.setForeground(new java.awt.Color(0, 0, 0));
        JpSecondBg.add(Jsepusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 360, 20));

        JpUserName.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JpUserName.setForeground(new java.awt.Color(102, 102, 102));
        JpUserName.setText("Username");
        JpSecondBg.add(JpUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 80, 20));

        JsePassword.setForeground(new java.awt.Color(0, 0, 0));
        JpSecondBg.add(JsePassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 410, 360, 20));

        JpPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        JpPassword.setForeground(new java.awt.Color(102, 102, 102));
        JpPassword.setText("Password");
        JpSecondBg.add(JpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 360, 160, 20));

        txtPassword.setBackground(new java.awt.Color(252, 252, 252));
        txtPassword.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        txtPassword.setBorder(null);
        txtPassword.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtPasswordAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        JpSecondBg.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 360, 30));

        JCheckShowPassword.setBackground(new java.awt.Color(255, 255, 255));
        JCheckShowPassword.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        JCheckShowPassword.setText("  Show Password");
        JCheckShowPassword.setBorder(null);
        JCheckShowPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JCheckShowPasswordActionPerformed(evt);
            }
        });
        JpSecondBg.add(JCheckShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, 30));

        JpLoginBtn.setBackground(new java.awt.Color(255, 153, 102));
        JpLoginBtn.setLayout(new java.awt.BorderLayout());

        btnLogin.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnLogin.setText("LOGIN");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        JpLoginBtn.add(btnLogin, java.awt.BorderLayout.CENTER);

        JpSecondBg.add(JpLoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 510, 170, 30));

        JpBackground.add(JpSecondBg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 0, 680, 680));

        JpUser.setOpaque(false);

        javax.swing.GroupLayout JpUserLayout = new javax.swing.GroupLayout(JpUser);
        JpUser.setLayout(JpUserLayout);
        JpUserLayout.setHorizontalGroup(
            JpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpUserLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        JpUserLayout.setVerticalGroup(
            JpUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JpUserLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JpBackground.add(JpUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 200, 200));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/b2.png"))); // NOI18N
        JpBackground.add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 680));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JpExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpExitBtnMouseClicked
         System.exit(0);
    }//GEN-LAST:event_JpExitBtnMouseClicked

    private void JpExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpExitBtnMouseEntered
        
    }//GEN-LAST:event_JpExitBtnMouseEntered

    private void txtJpExitBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJpExitBtnMouseExited
        //Regresa el boton para salir a su colorr
        JpExitBtn.setBackground(Color.white);
        JpExitBtn.setOpaque(false);
        txtJpExitBtn.setForeground(Color.black);
        
    }//GEN-LAST:event_txtJpExitBtnMouseExited

    private void txtJpExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJpExitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtJpExitBtnMouseClicked

    private void txtJpExitBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJpExitBtnMouseEntered
        //Pone el botón para salir de color rojo
        JpExitBtn.setBackground(Color.red);
        JpExitBtn.setOpaque(true);
        txtJpExitBtn.setForeground(Color.white);
        
    }//GEN-LAST:event_txtJpExitBtnMouseEntered

    private void txtJpMinBtNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJpMinBtNMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_txtJpMinBtNMouseClicked

    private void txtJpMinBtNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJpMinBtNMouseEntered
        //Pone el botón para minimizar de color gris
        JpMinBtN.setBackground(new Color(246,246,246));
        JpMinBtN.setOpaque(true);
        txtJpMinBtN.setForeground(Color.black);
    }//GEN-LAST:event_txtJpMinBtNMouseEntered

    private void txtJpMinBtNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtJpMinBtNMouseExited
        //Regresa el boton para sminimizar a su colorr
        //JpMinBtN.setBackground(Color.white);
        JpMinBtN.setBackground(new Color(225,225,225));
        txtJpMinBtN.setForeground(Color.black);
        JpMinBtN.setOpaque(false);
    }//GEN-LAST:event_txtJpMinBtNMouseExited

    private void JpHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpHeaderMousePressed
       //Detecta la posicion del mouse en la ventana
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_JpHeaderMousePressed

    private void JpHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JpHeaderMouseDragged
       //detecta la posicion del mouse en la pantalla
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        //envia al modelo para que reste la posicion de la ventana con la dela pantalla
        //int positionX = miCoordinador.restarX(x, mouseX);
        //int positionY = miCoordinador.restarY(y, mouseY);
        //mueve la ventana siguiendo el cursor
        this.setLocation(x - mouseX, y - mouseY);
    }//GEN-LAST:event_JpHeaderMouseDragged

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked

        String username = txtUserName.getText();
        String password = new String(txtPassword.getPassword()); 
        LoginCtrl login = new LoginCtrl();
        boolean check = login.validarLogin(username, password);
        
        if(check){
            dispose();
        }      
    }//GEN-LAST:event_btnLoginMouseClicked

    private void JCheckShowPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JCheckShowPasswordActionPerformed
        if(JCheckShowPassword.isSelected()){
            txtPassword.setEchoChar((char)0);
        }
        else{
            txtPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_JCheckShowPasswordActionPerformed

    private void txtPasswordAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtPasswordAncestorAdded
        txtPassword.setEchoChar('*');
    }//GEN-LAST:event_txtPasswordAncestorAdded

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JCheckBox JCheckShowPassword;
    private javax.swing.JPanel JpBackground;
    private javax.swing.JPanel JpExitBtn;
    private javax.swing.JPanel JpHeader;
    private javax.swing.JPanel JpLoginBtn;
    private javax.swing.JPanel JpMinBtN;
    private javax.swing.JLabel JpPassword;
    private javax.swing.JPanel JpSecondBg;
    private javax.swing.JLabel JpSenaIcon;
    private javax.swing.JPanel JpUser;
    private javax.swing.JLabel JpUserName;
    private javax.swing.JSeparator JsePassword;
    private javax.swing.JSeparator Jsepusername;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtDescription;
    private javax.swing.JLabel txtJpExitBtn;
    private javax.swing.JLabel txtJpMinBtN;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables

    public void setCoordinador(coordinador miCoordinador) {
        this.miCoordinador=miCoordinador;
    }
}
